"""Learn a linear map from an inferred tracking embedding back to the reward
embedding that generated the motion.

`data/z/<task>/<task>_<trial>.npy` (z0) comes from `reward_wr_inference` and so
requires knowing the humenv task reward up front
(`metamotivo_motion_rollout.py:compute_reward_z`). `data/z_inference/` comes from
`tracking_inference` on the motion alone -- no reward needed, but it is a
*tracking* embedding and behaves differently (a goal-like z is a fixed point,
a reward-like z is a limit cycle). This script asks whether the first can be
mapped onto the second:

    mean_z = project_z(mean_t z_track_t)          # occupancy embedding
    z_hat  = project_z(mean_z @ W)                # learned map
    W      = (1 - alpha) * I + alpha * W_ridge    # shrunk toward identity

Two things are load-bearing and easy to get wrong:

  * Pairs must be matched PER TRIAL. z0 is re-estimated from a fresh buffer
    subsample every call, so trial i's motion was generated by trial i's z0
    specifically. Comparing everything against trial 0's z0 drops cosine
    0.55 -> 0.30.
  * Splits must be over TASKS, not trials. With a trial-level split the same
    task's z0 appears in training and the model just memorises 54 prototypes
    (inflates test cosine to ~0.74). The effective sample size here is 54,
    not 540, which is also why the fit has to be shrunk toward identity and
    why anything nonlinear overfits.

Usage (from project root):
    python3 scripts/fit_z_map.py
    python3 scripts/fit_z_map.py --tree retargeting_z --out-dir outputs/fit_z_map_child

Writes <out-dir>/W.npz (maps + the held-out task list eval_z_map_rollout.py
uses) and <out-dir>/cosine_by_method.png.
"""

import argparse
import os

# Must precede the numpy import. The solves here are tiny (256x256); letting
# OpenBLAS fan out to its default 64 threads makes them ~300x SLOWER through
# thread thrashing (17.5s vs 0.06s for 20 solves on this machine).
for _var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
             "NUMEXPR_NUM_THREADS"):
    os.environ.setdefault(_var, "4")

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from pathlib import Path


def project_z(v):
    """Metamotivo keeps latents on the radius-sqrt(d) sphere (fb/model.py:126)."""
    v = np.asarray(v, dtype=np.float64)
    return v / np.linalg.norm(v, axis=-1, keepdims=True) * np.sqrt(v.shape[-1])


def unit(v):
    return v / np.linalg.norm(v, axis=-1, keepdims=True)


def row_cosine(A, B):
    return (unit(A) * unit(B)).sum(axis=1)


def apply_map(v, W):
    """Map a mean-z through W and put the result back on the sqrt(d) sphere.
    W is fitted on unit vectors, so v is normalised first -- keep this in sync
    with eval_z_map_rollout.py."""
    return project_z(unit(np.asarray(v, dtype=np.float64)) @ W)


def load_pairs(z_dir, tree_dir):
    """(X, Y, task_ids, task_names) with X = mean-z of the inferred tracking z,
    Y = the z0 of the SAME trial.

    Both are returned as UNIT vectors. The objective is cosine, which is scale
    invariant, but the ridge penalty is not: keeping the sqrt(d)=16 radius would
    scale X.T@X by 256 and silently shift the meaningful lambda range by the
    same factor."""
    tasks = sorted(p.name for p in tree_dir.iterdir() if p.is_dir())
    X, Y, tid = [], [], []
    for ti, task in enumerate(tasks):
        for npy in sorted((tree_dir / task).glob("*.npy")):
            z0_path = z_dir / task / npy.name
            if not z0_path.exists():
                print(f"  warn: no z0 for {task}/{npy.name}, skipping")
                continue
            Z = np.load(npy)
            if Z.ndim == 1:
                Z = Z[None]
            # trajectory mean, not the last frame: the last frame of
            # tracking_inference is a goal embedding (its averaging window has
            # collapsed to one frame) and drives the actor to a fixed point.
            X.append(unit(Z.mean(axis=0)))
            Y.append(unit(np.load(z0_path).reshape(-1)))
            tid.append(ti)
    return np.stack(X), np.stack(Y), np.array(tid), tasks


def baselines(Y, tid, n_tasks):
    """Two reference lines every number should be read against:
    ceiling = how well z0 reproduces ITSELF across trials of the same task
    floor   = cosine between z0 of different tasks (chance)."""
    same, protos = [], []
    for ti in range(n_tasks):
        V = unit(Y[tid == ti])
        if len(V) > 1:
            C = V @ V.T
            same.append(C[~np.eye(len(V), dtype=bool)].mean())
        protos.append(V.mean(axis=0))
    P = unit(np.stack(protos))
    C = P @ P.T
    off = C[~np.eye(n_tasks, dtype=bool)]
    return float(np.mean(same)), float(off.mean())


def fit_ridge(X, Y, lam):
    d = X.shape[1]
    return np.linalg.solve(X.T @ X + lam * np.eye(d), X.T @ Y)


def fit_procrustes(X, Y):
    U, _, Vt = np.linalg.svd(X.T @ Y)
    return U @ Vt


def shrink(W, alpha):
    return (1.0 - alpha) * np.eye(W.shape[0]) + alpha * W


def task_split(rng, n_tasks, n_train, tid):
    perm = rng.permutation(n_tasks)
    train_tasks = set(perm[:n_train].tolist())
    test_mask = np.array([t not in train_tasks for t in tid])
    return ~test_mask, test_mask, sorted(perm[n_train:].tolist())


def select_hparams(X, Y, tid, train_tasks, lams, alphas, seed, n_inner=4):
    """Nested CV: pick (lam, alpha) using task-level splits INSIDE the training
    tasks only, so the outer test tasks never influence the choice."""
    train_tasks = np.array(sorted(train_tasks))
    # Keep the inner training set close in size to the outer one; too small a
    # fraction tunes for less data than the final fit gets and over-shrinks.
    n_in = max(2, int(round(len(train_tasks) * 0.85)))
    scores = {}
    for s in range(n_inner):
        rng = np.random.default_rng(1000 * seed + s)
        perm = rng.permutation(len(train_tasks))
        inner_tr = set(train_tasks[perm[:n_in]].tolist())
        m_tr = np.array([t in inner_tr for t in tid])
        m_te = np.array([(t in set(train_tasks.tolist())) and (t not in inner_tr) for t in tid])
        if m_te.sum() == 0:
            continue
        for lam in lams:
            Wr = fit_ridge(X[m_tr], Y[m_tr], lam)
            for a in alphas:
                c = row_cosine(X[m_te] @ shrink(Wr, a), Y[m_te]).mean()
                scores.setdefault((lam, a), []).append(c)
    return max(scores, key=lambda k: np.mean(scores[k]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-root", default="data")
    ap.add_argument("--tree", default="z_inference", help="dir of inferred (T,256) z")
    ap.add_argument("--z-dir", default="z", help="dir of the target z0")
    ap.add_argument("--out-dir", default="outputs/fit_z_map")
    ap.add_argument("--n-splits", type=int, default=8)
    ap.add_argument("--n-train-tasks", type=int, default=38)
    ap.add_argument("--lams", type=float, nargs="+", default=[0.1, 0.3, 1.0, 3.0, 10.0])
    ap.add_argument("--alphas", type=float, nargs="+", default=[0.4, 0.5, 0.6, 0.7, 0.8, 1.0])
    ap.add_argument("--with-mlp", action="store_true",
                    help="also evaluate an MLP (expected to lose to identity)")
    args = ap.parse_args()

    root = Path(args.data_root)
    X, Y, tid, tasks = load_pairs(root / args.z_dir, root / args.tree)
    n_tasks = len(tasks)
    print(f"{len(X)} pairs over {n_tasks} tasks, dim {X.shape[1]}  "
          f"({args.tree} -> {args.z_dir})")

    ceiling, floor = baselines(Y, tid, n_tasks)
    print(f"ceiling  cos(z0_i, z0_j) same task, diff trial = {ceiling:.4f}")
    print(f"floor    cos(z0_i, z0_j) different tasks        = {floor:.4f}\n")

    results = {k: [] for k in ["identity", "procrustes", "ridge",
                               "shrinkage-ridge", "shrinkage-ridge (oracle)"]}
    if args.with_mlp:
        results["mlp"] = []
    picked, first_split = [], None

    for seed in range(args.n_splits):
        rng = np.random.default_rng(seed)
        tr, te, held_out = task_split(rng, n_tasks, args.n_train_tasks, tid)
        train_tasks = sorted(set(tid[tr].tolist()))
        if first_split is None:
            first_split = (seed, tr, te, held_out, train_tasks)

        results["identity"].append(row_cosine(X[te], Y[te]).mean())
        results["procrustes"].append(row_cosine(X[te] @ fit_procrustes(X[tr], Y[tr]), Y[te]).mean())

        best_lam_plain = max(args.lams,
                             key=lambda l: row_cosine(X[te] @ fit_ridge(X[tr], Y[tr], l), Y[te]).mean())
        results["ridge"].append(
            row_cosine(X[te] @ fit_ridge(X[tr], Y[tr], best_lam_plain), Y[te]).mean())

        lam, alpha = select_hparams(X, Y, tid, train_tasks, args.lams, args.alphas, seed)
        W = shrink(fit_ridge(X[tr], Y[tr], lam), alpha)
        results["shrinkage-ridge"].append(row_cosine(X[te] @ W, Y[te]).mean())
        picked.append((lam, alpha))

        # upper bound: best (lam, alpha) chosen ON the test tasks. Not a
        # generalisation number -- it bounds how much the nested CV leaves behind.
        results["shrinkage-ridge (oracle)"].append(max(
            row_cosine(X[te] @ shrink(fit_ridge(X[tr], Y[tr], l), a), Y[te]).mean()
            for l in args.lams for a in args.alphas))

        if args.with_mlp:
            import warnings
            warnings.filterwarnings("ignore")
            from sklearn.neural_network import MLPRegressor
            mlp = MLPRegressor(hidden_layer_sizes=(512,), alpha=1.0,
                               max_iter=800, random_state=0).fit(X[tr], Y[tr])
            results["mlp"].append(row_cosine(mlp.predict(X[te]), Y[te]).mean())

    # leaky trial-level split, reported only as a warning about how it misleads
    te2 = np.array([i % 10 >= 8 for i in range(len(X))])
    W_leaky = shrink(fit_ridge(X[~te2], Y[~te2], 1.0), 0.7)
    leaky = row_cosine(X[te2] @ W_leaky, Y[te2]).mean()

    print(f"test cosine over {args.n_splits} task-level splits "
          f"({args.n_train_tasks} train / {n_tasks - args.n_train_tasks} test tasks)")
    for name, vals in results.items():
        v = np.array(vals)
        print(f"  {name:16s} {v.mean():.4f} +/- {v.std():.4f}")
    lam_star, alpha_star = max(set(picked), key=picked.count)
    print(f"  hyperparams picked by nested CV (modal): lam={lam_star}, alpha={alpha_star}")
    print(f"\n  [LEAKY trial-level split] shrinkage-ridge = {leaky:.4f}  "
          f"<- inflated, do not report as generalisation")

    # Two maps: one fitted only on the first split's training tasks (used by
    # eval_z_map_rollout.py so the rollout tasks are genuinely held out), and
    # one fitted on everything (for downstream use on new motions).
    seed0, tr0, _, held_out0, train_tasks0 = first_split
    W_heldout = shrink(fit_ridge(X[tr0], Y[tr0], lam_star), alpha_star)
    W_full = shrink(fit_ridge(X, Y, lam_star), alpha_star)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    np.savez(
        out_dir / "W.npz",
        W_full=W_full, W_heldout=W_heldout,
        lam=lam_star, alpha=alpha_star, split_seed=seed0,
        tasks=np.array(tasks), held_out_tasks=np.array([tasks[i] for i in held_out0]),
        train_tasks=np.array([tasks[i] for i in train_tasks0]),
        ceiling=ceiling, floor=floor,
        **{f"cos_{k}": np.array(v) for k, v in results.items()},
    )
    print(f"\nwrote {out_dir / 'W.npz'}  (held-out tasks: {len(held_out0)})")

    names = list(results)
    means = [np.mean(results[k]) for k in names]
    errs = [np.std(results[k]) for k in names]
    tick_of = {"shrinkage-ridge": "shrinkage-ridge\n(nested CV)",
               "shrinkage-ridge (oracle)": "shrinkage-ridge\n(oracle)"}
    ticks = [tick_of.get(n, n) for n in names]
    plt.figure(figsize=(8.5, 5.5))
    bars = plt.bar(ticks, means, yerr=errs, capsize=4,
                   color=["#999999" if n == "identity" else "#4C72B0" for n in names])
    bars[names.index("shrinkage-ridge")].set_color("#DD8452")
    plt.axhline(ceiling, color="green", linestyle="--",
                label=f"z0 self-consistency ceiling ({ceiling:.3f})")
    plt.axhline(floor, color="red", linestyle=":", label=f"cross-task floor ({floor:.3f})")
    for i, (m, e) in enumerate(zip(means, errs)):
        plt.text(i, m + e + 0.015, f"{m:.3f}", ha="center", fontsize=9)
    plt.ylabel("test cosine to $z_0$ (held-out tasks)")
    plt.title(f"Recovering $z_0$ from {args.tree}\n"
              f"{args.n_splits} task-level splits, {len(X)} pairs / {n_tasks} tasks")
    plt.ylim(0, max(max(means) + 0.12, ceiling + 0.1))
    plt.legend(fontsize=8)
    plt.grid(axis="y", linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.savefig(out_dir / "cosine_by_method.png", dpi=200)
    plt.close()
    print(f"wrote {out_dir / 'cosine_by_method.png'}")


if __name__ == "__main__":
    main()
