"""Clips, bodies, and (clip, body, window) sampling.

Replaces the manifest-driven model/dataset.py CrossEmbodimentDataset for the
bilevel path. Three things change:

  1. It reads data/origin_motion/ (the SOURCE-body motion), not the pre-baked
     data/retargeted_motion/. Retargeting is now a runtime, differentiable
     function of p -- that is the whole point -- so a baked reference would
     be dead weight.
  2. beta actually varies. scripts/build_dataset.py:45 hardcoded
     MORPHOLOGY_LABEL="child" onto all 1530 manifest rows, so LatentAdapter's
     beta input carried literally zero information. Here every clip is paired
     with every training body: 540 clips x 10 bodies = 5400 pairs.
  3. No manifest, no build step, no 78 MB duplicate on disk. All 540 clips are
     540 x ~300 x 76 x 8 B = 98 MB; they just get loaded.

scripts/build_dataset.py is consequently unused by this path (and is currently
broken anyway -- its MORPHOLOGY_SRC at :44 points at
assets/robots/robot_child_parameter.json, which the 9495329 asset restructure
removed).
"""

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import mujoco
import numpy as np
import torch

from model.bilevel.torch_kin import TorchKinematics
from model.dataset import BETA_AXES, load_beta, load_task_list
from model.kinematics import EE_BODIES, FOOT_BODIES, ROOT_BODY

REPO_ROOT = Path(__file__).resolve().parents[2]

# Chain used to define a characteristic leg length per body. Segment lengths are
# the child's own body_pos offsets, so this scales correctly with morphology.
_LEG_CHAIN = ["L_Knee", "L_Ankle"]  # thigh + shank (body_pos is the offset FROM the parent)


def _chain_length(model: mujoco.MjModel, body_name: str, stop: str = ROOT_BODY) -> float:
    """Sum of |body_pos| walking up from `body_name` to `stop`, in the rest pose.

    A morphology-aware characteristic length for that limb -- used to make the
    end-effector reach term in semantics.S dimensionless, so that a legitimate
    limb-length change costs nothing while a change of posture costs.
    """
    bid = model.body(body_name).id
    stop_id = model.body(stop).id
    total = 0.0
    while bid != stop_id and bid != 0:
        total += float(np.linalg.norm(model.body_pos[bid]))
        bid = int(model.body_parentid[bid])
    return total


@dataclass
class BodySpec:
    """Everything the pipeline needs about one morphology."""
    name: str
    xml_path: Path
    beta: np.ndarray                 # (8,) in model/dataset.py BETA_AXES order
    model: mujoco.MjModel
    kin: TorchKinematics
    mass: float
    rest_h: float                    # rest-pose pelvis world z == MjModel.qpos0[2]
    leg_len: float
    limb_len: Dict[str, float]       # EE body name -> rest-pose chain length from Pelvis
    foot_rest_z: Dict[str, float]    # FOOT_BODIES name -> world z in the rest (standing) pose
    is_train: bool = True

    @property
    def ee_limb_lengths(self) -> np.ndarray:
        return np.array([self.limb_len[e] for e in EE_BODIES], dtype=np.float64)

    @property
    def foot_rest_heights(self) -> np.ndarray:
        return np.array([self.foot_rest_z[f] for f in FOOT_BODIES], dtype=np.float64)


def split_of(cfg, name: str) -> str:
    """Which side of the split a body is on. The single definition of that
    question -- scripts/write_body_splits.py writes it into parameter.json and
    load_body checks against it, so both must agree by construction.

    `source` is its own category, not `unused`: the source body is never
    trained on, but every retarget is measured FROM it (semantics.S compares
    against it), so calling it unused would be wrong.
    """
    if name == cfg.source_body:
        return "source"
    if name in cfg.train_bodies:
        return "train"
    if name in cfg.heldout_bodies:
        return "test"
    return "unused"


def _foot_rest_heights(model: mujoco.MjModel) -> Dict[str, float]:
    """Height of each foot body's origin ABOVE THE GROUND CONTACT PLANE, in the
    rest pose. The per-morphology zero point for semantics.contact_signal.

    A raw threshold like model/losses.py:153's `z_foot < 0.05` means something
    quite different for a 0.58 m child than a 1.17 m giant, so the contact
    indicator measures `z_foot - foot_rest_z` instead.

    The subtraction of the rest-pose lowest geom point is NOT cosmetic. The
    assets do not share a zero: `assets/robots/adult/robot.xml` is hand-authored
    with its feet 2 cm off the floor at qpos0 (rest min_geom_z = +0.020), while
    every body generated by scripts/scale_robot.py sits exactly at 0.000.
    Taking the raw foot z as the zero therefore biases the source and target
    contact signals apart by that 2 cm, which is enough to invert the gradient:
    measured, the source read as "in contact" with probability 0.98 against the
    target's 0.92, so the fidelity term pushed the reference DOWN, into the
    floor, at 717x the magnitude of the penetration term trying to lift it out.
    Referencing both to their own contact plane removes the asset discrepancy.
    """
    d = mujoco.MjData(model)
    mujoco.mj_resetData(model, d)
    mujoco.mj_forward(model, d)
    ground = _rest_min_geom_z(model, d)
    return {f: float(d.xpos[model.body(f).id][2]) - ground for f in FOOT_BODIES}


def _rest_min_geom_z(model: mujoco.MjModel, data: mujoco.MjData) -> float:
    """Lowest point over all non-floor geoms, for the current data. Numpy twin
    of TorchKinematics.min_geom_z (used here to avoid importing torch state)."""
    import itertools

    lo = np.inf
    for gid in range(model.ngeom):
        if mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, gid) == "floor":
            continue
        gtype = model.geom_type[gid]
        pos, mat, size = data.geom_xpos[gid], data.geom_xmat[gid].reshape(3, 3), model.geom_size[gid]
        if gtype == mujoco.mjtGeom.mjGEOM_BOX:
            for s in itertools.product([1, -1], repeat=3):
                lo = min(lo, (pos + mat @ (np.array(s) * size))[2])
        elif gtype == mujoco.mjtGeom.mjGEOM_CAPSULE:
            lo = min(lo,
                     (pos + mat @ np.array([0, 0, size[1]]))[2] - size[0],
                     (pos + mat @ np.array([0, 0, -size[1]]))[2] - size[0])
        elif gtype == mujoco.mjtGeom.mjGEOM_SPHERE:
            lo = min(lo, pos[2] - size[0])
        else:
            lo = min(lo, pos[2])
    return float(lo)


def load_body(cfg, name: str, is_train: bool = True, dtype=torch.float64,
              check_split: bool = True) -> BodySpec:
    root = REPO_ROOT / cfg.robots_dir / name
    xml = root / "robot.xml"

    # The asset and the config must agree on which side of the split this body
    # is on. `"split"` sat unread in parameter.json since commit 9495329,
    # marking pear_shaped and teen as "val" while every actual configuration
    # trained on them -- a dead field contradicting the live one. It is now
    # written by scripts/write_body_splits.py and checked here so the two
    # cannot drift apart again without someone noticing.
    if check_split:
        par = json.loads((root / "parameter.json").read_text())
        recorded = par.get("split")
        expected = split_of(cfg, name)
        if recorded is not None and recorded != expected:
            raise ValueError(
                f"{root/'parameter.json'} says split={recorded!r} but "
                f"BilevelConfig puts {name!r} in {expected!r}. Re-run "
                f"scripts/write_body_splits.py after changing the config."
            )

    model = mujoco.MjModel.from_xml_path(str(xml))
    return BodySpec(
        name=name,
        xml_path=xml,
        beta=load_beta(root / "parameter.json"),
        model=model,
        kin=TorchKinematics(model, dtype=dtype),
        mass=float(model.body_mass.sum()),
        rest_h=float(model.qpos0[2]),
        leg_len=sum(float(np.linalg.norm(model.body_pos[model.body(b).id])) for b in _LEG_CHAIN),
        limb_len={e: _chain_length(model, e) for e in EE_BODIES},
        foot_rest_z=_foot_rest_heights(model),
        is_train=is_train,
    )


@dataclass
class Clip:
    task: str
    trial: int
    qpos: np.ndarray                 # (T, 76) float64, on the SOURCE body
    z0: np.ndarray                   # (256,) float32, ||z|| == sqrt(256) == 16


class WindowDataset:
    """540 source clips x N bodies, sampled as fixed-length windows.

    A "sample" is a triple (clip, body, t0). The batch it produces is the source
    window `src_qpos` -- retargeting happens downstream in Retargeter, per
    iteration, with the current p.
    """

    def __init__(
        self,
        cfg,
        bodies: Optional[Sequence[str]] = None,
        tasks: Optional[Sequence[str]] = None,
        verbose: bool = True,
    ):
        self.cfg = cfg
        self.horizon = cfg.horizon

        # Source window length. We need ref[0..H] (H+1 frames): ref[0] for RSI,
        # ref[t+1] as the target for step t. The extra margin only exists so the
        # Stage-3 time warp (tau up to 1.25) has source frames to interpolate.
        margin = 0
        if cfg.enable_time_warp:
            margin = int(np.ceil(cfg.horizon * (np.exp(cfg.box_log_tau) - 1.0))) + 2
        self.src_window_len = cfg.horizon + 1 + margin

        # ---- bodies ------------------------------------------------------
        names = list(bodies) if bodies is not None else list(cfg.train_bodies)
        self.bodies: List[BodySpec] = [load_body(cfg, n, is_train=True) for n in names]
        self.body_index = {b.name: i for i, b in enumerate(self.bodies)}
        self.source = load_body(cfg, cfg.source_body, is_train=False)
        self.beta_dim = len(BETA_AXES)

        # ---- task filter -------------------------------------------------
        task_filter = set(tasks) if tasks is not None else None

        # ---- clips -------------------------------------------------------
        motion_root = REPO_ROOT / cfg.origin_motion_dir
        z_root = REPO_ROOT / cfg.z_dir
        if not motion_root.exists():
            raise FileNotFoundError(
                f"{motion_root} not found -- generate it with scripts/metamotivo_motion_rollout.py"
            )

        self.clips: List[Clip] = []
        skipped_no_z = 0
        skipped_short = 0
        for npz_path in sorted(motion_root.rglob("*.npz")):
            task = npz_path.parent.name
            if task_filter is not None and task not in task_filter:
                continue
            trial = int(npz_path.stem.rsplit("_", 1)[1])
            z_path = z_root / task / f"{npz_path.stem}.npy"
            if not z_path.exists():
                skipped_no_z += 1
                continue
            qpos = np.load(npz_path)["qpos"].astype(np.float64)
            if qpos.shape[0] < self.src_window_len:
                skipped_short += 1
                continue
            self.clips.append(
                Clip(task=task, trial=trial, qpos=qpos,
                     z0=np.load(z_path).reshape(-1).astype(np.float32))
            )

        if not self.clips:
            raise ValueError(f"no usable clips under {motion_root} (task_filter={task_filter})")

        self.clip_lengths = np.array([c.qpos.shape[0] for c in self.clips], dtype=np.int64)
        # Highest valid window start per clip.
        self.max_t0 = self.clip_lengths - self.src_window_len

        if verbose:
            mb = sum(c.qpos.nbytes for c in self.clips) / 1e6
            print(
                f"WindowDataset: {len(self.clips)} clips x {len(self.bodies)} bodies "
                f"= {len(self.clips) * len(self.bodies)} pairs, {mb:.0f} MB resident, "
                f"window={self.src_window_len} frames"
                + (f", skipped {skipped_no_z} without z" if skipped_no_z else "")
                + (f", {skipped_short} too short" if skipped_short else "")
            )

    # ------------------------------------------------------------------ sampling

    def __len__(self) -> int:
        return len(self.clips) * len(self.bodies)

    def body_assignment(self, n_envs: int) -> np.ndarray:
        """Fixed env-slot -> body map, (n_envs,) int64. CONTIGUOUS, by design.

        A MuJoCo sim is bound to one MjModel, so letting an env slot change
        morphology between iterations would mean every worker holding one
        MjModel/MjData per (slot, body) and swapping on reset. Pinning the
        assignment instead means each worker loads 1-2 models once and never
        switches. Contiguous rather than round-robin so that a worker's
        `sims_per_worker` consecutive slots almost always share a single body.

        It also gives ES what it needs for free: each body owns a contiguous
        slot range, so a per-body perturbation group is a slice (upper.py).
        """
        nb = len(self.bodies)
        return (np.arange(n_envs) * nb) // n_envs

    def sample(self, n: int, rng: np.random.Generator, body_idx: Optional[np.ndarray] = None):
        """-> (clip_idx (n,), body_idx (n,), t0 (n,)).

        `body_idx` should be the fixed assignment from body_assignment(); it is
        NOT resampled per iteration. Bodies stay stratified across the batch
        (every body appears every iteration), which the antithetic-ES estimator
        requires and which keeps the per-(clip, body) advantage EMA in ppo.py
        from going stale on rarely-sampled bodies.
        """
        if body_idx is None:
            body_idx = self.body_assignment(n)
        clip_idx = rng.integers(0, len(self.clips), size=n)
        t0 = (rng.random(n) * (self.max_t0[clip_idx] + 1)).astype(np.int64)
        return clip_idx, np.asarray(body_idx), t0

    def build_batch(self, clip_idx, body_idx, t0):
        """-> dict of numpy arrays for one iteration.

        src_qpos : (n, W, 76) float64  source-body motion window
        beta     : (n, 8)     float32
        z0       : (n, 256)   float32
        pair_id  : (n,)       int64    clip*n_bodies + body, for the advantage EMA
        """
        n = len(clip_idx)
        W = self.src_window_len
        src = np.empty((n, W, 76), dtype=np.float64)
        for i, (ci, t) in enumerate(zip(clip_idx, t0)):
            src[i] = self.clips[ci].qpos[t:t + W]
        return {
            "src_qpos": src,
            "beta": np.stack([self.bodies[b].beta for b in body_idx]).astype(np.float32),
            "z0": np.stack([self.clips[c].z0 for c in clip_idx]),
            "pair_id": clip_idx.astype(np.int64) * len(self.bodies) + body_idx.astype(np.int64),
            "clip_idx": np.asarray(clip_idx),
            "body_idx": np.asarray(body_idx),
            "t0": np.asarray(t0),
        }

    # ------------------------------------------------------------------ helpers

    def tasks(self) -> List[str]:
        return sorted({c.task for c in self.clips})

    def body_names(self) -> List[str]:
        return [b.name for b in self.bodies]


def load_splits(cfg) -> Tuple[Optional[List[str]], Optional[List[str]]]:
    """(train_tasks, test_tasks) from datasets/.../splits, or (None, None).

    Same task-level split as scripts/split_tasks.py (43/11 of the 54 official
    humenv tasks), reused so held-out numbers stay comparable with the
    model/evaluate.py + model/baseline.py baselines in outputs/.
    """
    d = REPO_ROOT / cfg.splits_dir
    tr, te = d / "train_tasks.txt", d / "test_tasks.txt"
    if not tr.exists() or not te.exists():
        print(f"WARNING: no train/test split found at {d} -- using all tasks for training")
        return None, None
    return load_task_list(tr), load_task_list(te)


def ref_qvel_from_qpos(model: mujoco.MjModel, q0: np.ndarray, q1: np.ndarray, dt: float) -> np.ndarray:
    """Finite-difference velocity in MuJoCo's own qvel coordinates. -> (nv,).

    MUST go through mj_differentiatePos, not (q1 - q0)/dt: the free joint's
    qvel[3:6] is a BODY-LOCAL angular velocity, which a 4-component quaternion
    difference simply cannot produce. scripts/check_retarget_actuator_feasibility.py
    documents the same pitfall.
    """
    v = np.zeros(model.nv, dtype=np.float64)
    mujoco.mj_differentiatePos(model, v, dt, np.ascontiguousarray(q0), np.ascontiguousarray(q1))
    return v


def batch_ref_qvel(model: mujoco.MjModel, ref: np.ndarray, dt: float) -> np.ndarray:
    """ref: (B, T, nq) -> (B, nv) velocity at the FIRST frame of each window."""
    return np.stack([ref_qvel_from_qpos(model, ref[i, 0], ref[i, 1], dt) for i in range(ref.shape[0])])
